# Generated by chezmoi. Edit the source template, not this deployed file.

$env.config.show_banner = false
$env.config.edit_mode = "vi"
$env.config.buffer_editor = {{ .terminalEditor | quote }}
$env.config.cursor_shape = {
    emacs: blink_block
    vi_insert: blink_block
    vi_normal: blink_block
}

$env.config.history = {
    file_format: sqlite
    max_size: 1_000_000
    sync_on_enter: true
    isolation: false
}

$env.config.completions = {
    case_sensitive: false
    quick: true
    partial: true
    algorithm: "fuzzy"
    external: {
        enable: true
        max_results: 100
    }
}

# WezTerm stable 20240203 on Windows can redraw the cursor/scrollback
# incorrectly when Nushell emits OSC 133 semantic prompt sequences.
if $nu.os-info.name == "windows" {
    $env.config.shell_integration.osc133 = false
}

$env.EDITOR = {{ .terminalEditor | quote }}
$env.VISUAL = {{ .terminalEditor | quote }}

# Keep the proxy endpoint machine-specific through chezmoi's initialization data.
$env.PROXY_URL = {{ .proxyUrl | quote }}

def --env proxy-on [--quiet] {
    let proxy_url = $env.PROXY_URL
    load-env {
        HTTP_PROXY: $proxy_url
        HTTPS_PROXY: $proxy_url
        ALL_PROXY: $proxy_url
        http_proxy: $proxy_url
        https_proxy: $proxy_url
        all_proxy: $proxy_url
        NO_PROXY: "localhost,127.0.0.1,::1"
        no_proxy: "localhost,127.0.0.1,::1"
    }
    if not $quiet {
        print $"🌐 Terminal proxy enabled (($proxy_url))"
    }
}

def --env proxy-off [] {
    hide-env --ignore-errors HTTP_PROXY HTTPS_PROXY ALL_PROXY
    hide-env --ignore-errors http_proxy https_proxy all_proxy
    hide-env --ignore-errors NO_PROXY no_proxy
    print "🔒 Terminal proxy disabled"
}

{{- if .proxyEnabled }}
proxy-on --quiet
{{- end }}

# Normalize Zellij's configuration path on all platforms.
$env.ZELLIJ_CONFIG_DIR = ($nu.home-dir | path join ".config" "zellij")

# Common executable locations. Add only paths that exist.
let candidate_paths = if $nu.os-info.name == "windows" {
    [
        ($nu.home-dir | path join ".cargo" "bin")
        ($nu.home-dir | path join "scoop" "shims")
        ($nu.home-dir | path join "AppData" "Local" "Microsoft" "WinGet" "Links")
    ]
} else {
    [
        ($nu.home-dir | path join ".local" "bin")
        ($nu.home-dir | path join ".cargo" "bin")
        ($nu.home-dir | path join ".linuxbrew" "bin")
        "/home/linuxbrew/.linuxbrew/bin"
        "/opt/homebrew/bin"
        "/usr/local/bin"
    ]
}

for p in $candidate_paths {
    if ($p | path exists) and ($p not-in $env.PATH) {
        $env.PATH = ($env.PATH | prepend $p)
    }
}

# External commands should be invoked explicitly inside helper commands.
def --env zj [name: string = "main"] {
    ^zellij attach $name --create
}

def --env zjd [name: string] {
    let existing = try {
        ^zellij list-sessions --short
        | lines
        | each {|line| $line | str trim }
    } catch {
        []
    }

    if $name in $existing {
        ^zellij attach $name
    } else {
        ^zellij --session $name --layout dev
    }
}

def zls [] {
    ^zellij list-sessions
}

def zkill [name: string] {
    ^zellij delete-session $name --force
}

def croot [] {
    chezmoi source-path
}

def ce [...paths: path] {
    if ($paths | is-empty) {
        ^{{ .guiEditor }} (chezmoi source-path)
    } else {
        for p in $paths {
            chezmoi edit $p
        }
    }
}

alias capply = chezmoi apply
alias cdiff = chezmoi diff
alias cupdate = chezmoi update
alias cstatus = chezmoi status

{{ template "nushell-compat.nu" . }}

# Generated by the platform-specific integration script during chezmoi apply.
source ~/.zoxide.nu
